swagger: "2.0"
info:
  title: "Argent Bank Transactions API"
  description: "API for managing user transactions"
  version: "1.0.0"
host: "localhost:3001"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /transactions:
    get:
      tags:
        - "Transactions"
      summary: "Get all transactions for the current month"
      description: "Retrieve a list of all transactions for the current month, grouped by account."
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Bearer JWT token"
      responses:
        200:
          description: "Transactions retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"
    post:
      tags:
        - "Transactions"
      summary: "Add a new transaction"
      description: "Create a new transaction."
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Bearer JWT token"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/NewTransaction"
      responses:
        201:
          description: "Transaction created successfully"
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized"
        400:
          description: "Invalid input"
        500:
          description: "Internal Server Error"
  /transactions/{id}:
    get:
      tags:
        - "Transactions"
      summary: "Get transaction details"
      description: "Retrieve details of a specific transaction."
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Bearer JWT token"
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "Transaction ID"
      responses:
        200:
          description: "Transaction details retrieved successfully"
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
    put:
      tags:
        - "Transactions"
      summary: "Update a transaction"
      description: "Update details of a specific transaction."
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Bearer JWT token"
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "Transaction ID"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        200:
          description: "Transaction updated successfully"
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized"
        400:
          description: "Invalid input"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
    delete:
      tags:
        - "Transactions"
      summary: "Delete a transaction"
      description: "Delete a specific transaction."
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Bearer JWT token"
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "Transaction ID"
      responses:
        204:
          description: "Transaction deleted successfully"
        401:
          description: "Unauthorized"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
      date:
        type: "string"
        format: "date"
      description:
        type: "string"
      amount:
        type: "number"
        format: "double"
      balance:
        type: "number"
        format: "double"
      category:
        type: "string"
      notes:
        type: "string"
  NewTransaction:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date"
      description:
        type: "string"
      amount:
        type: "number"
        format: "double"
      category:
        type: "string"
      notes:
        type: "string"
